title: Internationalist Communist Library
description: Official shared library for any and all Internationalist Communists

baseurl: "/internationalist-library"
url: "https://intcomden.github.io"

collections:
  sections:
    output: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
