title: Internationalist Communist Library
description: Official shared library for the Internationalist Communist Discord server

baseurl: "/internationalist-library"
url: "https://intcomden.github.io"

collections:
  texts:
    output: true
    permalink: "/:language/:slug/"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
