backend:
  name: github
  repo: intcomden/internationalist-library
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

# This enables the token login option
auth_method: token   # Important line for PAT support
